# Generated by Django 3.0.7 on 2020-06-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
